function build_turbofan_model()
%BUILD_TURBOFAN_MODEL  Programmatically construct TurbofanCycle08.slx: an
%   independently-implemented Simulink cross-check of project 08's
%   twin-spool cycle (projects/08-cycle-model/src/cycle.py:solve_cycle),
%   at its exact reference design point, so the results can be compared
%   line-for-line against projects/08-cycle-model/README.md.
%
%   Run this once to generate the model, then run_reference_design() to
%   simulate it and print the comparison table. Re-run this function
%   (it closes and rebuilds the model each time) after editing the
%   design-point constants below.
%
%   CAVEAT: this script was written and carefully reviewed but NOT
%   executed in MATLAB -- see ../README.md, "What's actually verified
%   here." The physics in compress.m / expand_for_work.m / combust.m /
%   nozzle_exit.m is a direct, careful port of already-tested Python and
%   is the trustworthy part -- test_physics_standalone.m exercises it
%   with zero Simulink involved. The block-construction calls below
%   (add_block, the Stateflow EMChart route for setting MATLAB Function
%   block code, add_line) are the more likely place for a MATLAB- or
%   Simulink-version-specific hiccup. If something here errors, the
%   README lists the known risk points and what to try.

mdl = 'TurbofanCycle08';
if bdIsLoaded(mdl)
    close_system(mdl, 0);
end
new_system(mdl);
open_system(mdl);

% ---- Reference design point -- see TurbofanDesignPoint in
% projects/08-cycle-model/src/cycle.py. Baked into the generated blocks
% as literal constants rather than wired in as Simulink signals: this is
% a single point-design comparison, not a parametric study. To try a
% different design point, edit these values and re-run this function.
ALTITUDE = 10668.0;
MACH = 0.78;
CORE_MASS_FLOW = 40.0;
BYPASS_RATIO = 6.0;
FAN_PR = 1.6;
BOOSTER_PR = 1.6;
HPC_PR = 14.0;
TET = 1650.0;

INTAKE_RECOVERY = 0.98;
FAN_EFF = 0.90;
BOOSTER_EFF = 0.88;
HPC_EFF = 0.87;
COMBUSTOR_EFF = 0.99;
HPT_EFF = 0.90;
LPT_EFF = 0.91;
MECH_EFF = 0.995;
CORE_NOZZLE_EFF = 0.98;
BYPASS_NOZZLE_EFF = 0.98;
COMBUSTOR_PLOSS = 0.04;
BYPASS_DUCT_PLOSS = 0.01;
FUEL_LHV = 43.0e6;

[CP_COLD, GAMMA_COLD] = gas_properties('air');
[CP_HOT, GAMMA_HOT] = gas_properties('combustion');

% ---- Layout: two rows, core path on row 1, bypass branch on row 2 ----
X0 = 30; DX = 170; Y0 = 40; DY = 150; W = 140; H = 60;
pos = @(col, row) [X0 + (col-1)*DX, Y0 + (row-1)*DY, ...
                   X0 + (col-1)*DX + W, Y0 + (row-1)*DY + H];

% ---- Intake: freestream to fan-face stagnation conditions ----
add_fcn_block(mdl, 'Intake', pos(1, 1), sprintf([ ...
    'function [fan_face, v0, p_ambient] = fcn()\n' ...
    '  altitude = %.8g; mach = %.8g;\n' ...
    '  cp = %.8g; gamma = %.8g; recovery = %.8g;\n' ...
    '  [t_static, p_static] = isa_atmosphere(altitude);\n' ...
    '  sound_speed = sqrt(gamma * (cp*(1-1/gamma)) * t_static);\n' ...
    '  v0 = mach * sound_speed;\n' ...
    '  t0 = t_static * (1 + 0.5*(gamma-1)*mach^2);\n' ...
    '  p0 = p_static * (t0/t_static)^(gamma/(gamma-1));\n' ...
    '  fan_face = [t0, p0*recovery];\n' ...
    '  p_ambient = p_static;\n' ...
    'end'], ALTITUDE, MACH, CP_COLD, GAMMA_COLD, INTAKE_RECOVERY));

% ---- Fan ----
add_fcn_block(mdl, 'Fan', pos(2, 1), sprintf([ ...
    'function fan_exit = fcn(fan_face)\n' ...
    '  fan_exit = compress(fan_face, %.8g, %.8g, %.8g, %.8g);\n' ...
    'end'], FAN_PR, FAN_EFF, CP_COLD, GAMMA_COLD));

% ---- Bypass branch: duct pressure loss + bypass nozzle, in one block
% since nothing else downstream needs the intermediate duct-exit state ----
add_fcn_block(mdl, 'BypassPath', pos(3, 2), sprintf([ ...
    'function bypass_result = fcn(fan_exit, p_ambient)\n' ...
    '  duct_exit = [fan_exit(1), fan_exit(2)*(1-%.8g)];\n' ...
    '  bypass_result = nozzle_exit(duct_exit, p_ambient, %.8g, %.8g, %.8g);\n' ...
    'end'], BYPASS_DUCT_PLOSS, BYPASS_NOZZLE_EFF, CP_COLD, GAMMA_COLD));

% ---- Core compression: booster then HPC ----
add_fcn_block(mdl, 'CoreCompression', pos(3, 1), sprintf([ ...
    'function [booster_exit, hpc_exit] = fcn(fan_exit)\n' ...
    '  booster_exit = compress(fan_exit, %.8g, %.8g, %.8g, %.8g);\n' ...
    '  hpc_exit = compress(booster_exit, %.8g, %.8g, %.8g, %.8g);\n' ...
    'end'], BOOSTER_PR, BOOSTER_EFF, CP_COLD, GAMMA_COLD, ...
    HPC_PR, HPC_EFF, CP_COLD, GAMMA_COLD));

% ---- Combustor + HPT: HPT is work-matched to the HPC it drives, which
% needs hpc_exit and booster_exit already available at this block ----
add_fcn_block(mdl, 'CombustorAndHPT', pos(4, 1), sprintf([ ...
    'function [combustor_exit, f, turbine_mass_flow, hpt_exit] = fcn(hpc_exit, booster_exit)\n' ...
    '  [combustor_exit, f] = combust(hpc_exit, %.8g, %.8g, %.8g, %.8g, %.8g, %.8g);\n' ...
    '  turbine_mass_flow = %.8g * (1 + f);\n' ...
    '  hpc_power = %.8g * %.8g * (hpc_exit(1) - booster_exit(1));\n' ...
    '  hpt_work_required = (hpc_power / %.8g) / turbine_mass_flow;\n' ...
    '  hpt_exit = expand_for_work(combustor_exit, hpt_work_required, %.8g, %.8g, %.8g);\n' ...
    'end'], TET, FUEL_LHV, COMBUSTOR_EFF, COMBUSTOR_PLOSS, CP_COLD, CP_HOT, ...
    CORE_MASS_FLOW, CORE_MASS_FLOW, CP_COLD, MECH_EFF, HPT_EFF, CP_HOT, GAMMA_HOT));

% ---- LPT: work-matched to the fan + booster it drives ----
add_fcn_block(mdl, 'LPT', pos(5, 1), sprintf([ ...
    'function lpt_exit = fcn(fan_face, fan_exit, booster_exit, hpt_exit, turbine_mass_flow)\n' ...
    '  total_fan_mass_flow = %.8g * (1 + %.8g);\n' ...
    '  fan_power = total_fan_mass_flow * %.8g * (fan_exit(1) - fan_face(1));\n' ...
    '  booster_power = %.8g * %.8g * (booster_exit(1) - fan_exit(1));\n' ...
    '  lpt_work_required = ((fan_power + booster_power) / %.8g) / turbine_mass_flow;\n' ...
    '  lpt_exit = expand_for_work(hpt_exit, lpt_work_required, %.8g, %.8g, %.8g);\n' ...
    'end'], CORE_MASS_FLOW, BYPASS_RATIO, CP_COLD, CORE_MASS_FLOW, CP_COLD, ...
    MECH_EFF, LPT_EFF, CP_HOT, GAMMA_HOT));

% ---- Core nozzle ----
add_fcn_block(mdl, 'CoreNozzle', pos(6, 1), sprintf([ ...
    'function core_result = fcn(lpt_exit, p_ambient)\n' ...
    '  core_result = nozzle_exit(lpt_exit, p_ambient, %.8g, %.8g, %.8g);\n' ...
    'end'], CORE_NOZZLE_EFF, CP_HOT, GAMMA_HOT));

% ---- Thrust, TSFC and efficiency, matching cycle.py's TurbofanCycle
% properties exactly -- including the pressure-thrust term applying only
% when a nozzle is choked, and the bypass_ratio=0 divide-by-zero guard ----
add_fcn_block(mdl, 'PerformanceSummary', pos(7, 1), sprintf([ ...
    'function results = fcn(core_result, bypass_result, turbine_mass_flow, p_ambient, v0, f)\n' ...
    '  core_mass_flow = %.8g; bypass_ratio = %.8g;\n' ...
    '  cp_hot = %.8g; gamma_hot = %.8g; r_hot = cp_hot*(1-1/gamma_hot);\n' ...
    '  cp_cold = %.8g; gamma_cold = %.8g; r_cold = cp_cold*(1-1/gamma_cold);\n' ...
    '  bypass_mass_flow = core_mass_flow * bypass_ratio;\n' ...
    '  total_intake_mass_flow = core_mass_flow + bypass_mass_flow;\n' ...
    '  fuel_mass_flow = core_mass_flow * f;\n' ...
    '  core_gross = turbine_mass_flow * core_result(3);\n' ...
    '  if core_result(4) > 0.5\n' ...
    '    core_density = core_result(2) / (r_hot * core_result(1));\n' ...
    '    core_area = turbine_mass_flow / (core_density * core_result(3));\n' ...
    '    core_gross = core_gross + core_area * (core_result(2) - p_ambient);\n' ...
    '  end\n' ...
    '  bypass_gross = bypass_mass_flow * bypass_result(3);\n' ...
    '  if bypass_result(4) > 0.5\n' ...
    '    bypass_density = bypass_result(2) / (r_cold * bypass_result(1));\n' ...
    '    bypass_area = bypass_mass_flow / (bypass_density * bypass_result(3));\n' ...
    '    bypass_gross = bypass_gross + bypass_area * (bypass_result(2) - p_ambient);\n' ...
    '  end\n' ...
    '  ram_drag = total_intake_mass_flow * v0;\n' ...
    '  net_thrust = core_gross + bypass_gross - ram_drag;\n' ...
    '  tsfc_g_per_kns = (fuel_mass_flow / net_thrust) * 1.0e6;\n' ...
    '  core_eff_v = core_gross / turbine_mass_flow;\n' ...
    '  if bypass_mass_flow == 0\n' ...
    '    bypass_eff_v = 0;\n' ...
    '  else\n' ...
    '    bypass_eff_v = bypass_gross / bypass_mass_flow;\n' ...
    '  end\n' ...
    '  jet_kinetic_power = 0.5*turbine_mass_flow*core_eff_v^2 + 0.5*bypass_mass_flow*bypass_eff_v^2 - 0.5*total_intake_mass_flow*v0^2;\n' ...
    '  fuel_heat_rate = fuel_mass_flow * %.8g;\n' ...
    '  thermal_eff = jet_kinetic_power / fuel_heat_rate;\n' ...
    '  thrust_power = net_thrust * v0;\n' ...
    '  propulsive_eff = thrust_power / jet_kinetic_power;\n' ...
    '  overall_eff = thrust_power / fuel_heat_rate;\n' ...
    '  results = [net_thrust, tsfc_g_per_kns, thermal_eff*100, propulsive_eff*100, overall_eff*100, f*100, core_gross, bypass_gross];\n' ...
    'end'], CORE_MASS_FLOW, BYPASS_RATIO, CP_HOT, GAMMA_HOT, CP_COLD, GAMMA_COLD, FUEL_LHV));

% ---- Sink: writes the results row to the base workspace so
% run_reference_design.m can read it back after sim() ----
add_block('simulink/Sinks/To Workspace', [mdl '/Results'], ...
    'Position', pos(8, 1), ...
    'VariableName', 'cycle_results', ...
    'SaveFormat', 'Array');

% ---- Terminator for the one output nothing downstream needs
% (combustor_exit -- only its consequences, f/turbine_mass_flow/hpt_exit,
% are used further on) ----
add_block('simulink/Sinks/Terminator', [mdl '/UnusedCombustorExit'], ...
    'Position', pos(4, 2));

% ---- Wiring ----
connect(mdl, 'Intake', 1, 'Fan', 1);              % fan_face
connect(mdl, 'Intake', 1, 'LPT', 1);               % fan_face, tapped again
connect(mdl, 'Intake', 2, 'PerformanceSummary', 5); % v0
connect(mdl, 'Intake', 3, 'BypassPath', 2);         % p_ambient
connect(mdl, 'Intake', 3, 'CoreNozzle', 2);         % p_ambient
connect(mdl, 'Intake', 3, 'PerformanceSummary', 4); % p_ambient

connect(mdl, 'Fan', 1, 'BypassPath', 1);            % fan_exit
connect(mdl, 'Fan', 1, 'CoreCompression', 1);       % fan_exit
connect(mdl, 'Fan', 1, 'LPT', 2);                   % fan_exit, tapped again

connect(mdl, 'CoreCompression', 1, 'LPT', 3);              % booster_exit
connect(mdl, 'CoreCompression', 1, 'CombustorAndHPT', 2);  % booster_exit
connect(mdl, 'CoreCompression', 2, 'CombustorAndHPT', 1);  % hpc_exit

connect(mdl, 'CombustorAndHPT', 1, 'UnusedCombustorExit', 1); % combustor_exit
connect(mdl, 'CombustorAndHPT', 2, 'PerformanceSummary', 6);  % f
connect(mdl, 'CombustorAndHPT', 3, 'LPT', 5);                 % turbine_mass_flow
connect(mdl, 'CombustorAndHPT', 3, 'PerformanceSummary', 3);  % turbine_mass_flow
connect(mdl, 'CombustorAndHPT', 4, 'LPT', 4);                 % hpt_exit

connect(mdl, 'LPT', 1, 'CoreNozzle', 1);            % lpt_exit

connect(mdl, 'BypassPath', 1, 'PerformanceSummary', 2);  % bypass_result
connect(mdl, 'CoreNozzle', 1, 'PerformanceSummary', 1);  % core_result

connect(mdl, 'PerformanceSummary', 1, 'Results', 1);

save_system(mdl, fullfile(fileparts(mfilename('fullpath')), [mdl '.slx']));
fprintf('Wrote %s.slx\n', mdl);
end


function add_fcn_block(mdl, name, position, script)
%ADD_FCN_BLOCK  Create a MATLAB Function block and set its body via the
%   Stateflow EMChart API -- the documented way to author a MATLAB
%   Function block's code from a script rather than by hand in the GUI.
blk = [mdl '/' name];
add_block('simulink/User-Defined Functions/MATLAB Function', blk, ...
    'Position', position);
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blk);
chart.Script = script;
end


function connect(mdl, srcBlock, srcPort, dstBlock, dstPort)
%CONNECT  add_line by port number, srcBlock/dstBlock given as short names
%   (not full mdl-prefixed paths) for readability at the call site above.
add_line(mdl, ...
    sprintf('%s/%d', srcBlock, srcPort), ...
    sprintf('%s/%d', dstBlock, dstPort), ...
    'autorouting', 'on');
end
