#!/usr/bin/env python3
"""Is FINDINGS.md's index of numbered findings current, without rebuilding it?

`tools/build_findings.py` imports the verification solvers to rank the
disagreements, and that import runs them: the full regeneration takes about
two minutes, which is far too long to sit in front of every commit. But the
half of the document that actually goes stale is the cheap half. A commit
adds a numbered finding to a `STEP0.md`, the index table and the count
sentence beside it no longer match, and CI says so sixteen minutes later.

So this re-derives only that table, straight from the `STEP0.md` files, in
about fifty milliseconds. The ranked-disagreement half is left to CI, which
is the right division: that half moves when solver code or data moves, and
it is regenerated by the same run that produced the numbers.

The scan rule is deliberately the same as `findings_index()` in
`tools/build_findings.py` -- first occurrence of a number owns it. If the two
ever disagree, this check reports it as stale and the full generator settles
it, which is the safe direction.

    python3 .githooks/findings-index-check.py <project-root>
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()

line_pat = re.compile(r"^\s{0,5}(\d{1,3})\.\s+(.*)$")
row_pat = re.compile(r"^\|\s*(\d{1,3})\s*\|\s*([A-Za-z0-9_]+)\s*\|")
count_pat = re.compile(r"^(\d+) findings, in the")


def from_the_step0_files():
    out = {}
    for f in sorted((ROOT / "solvers").glob("*/STEP0.md")):
        for line in f.read_text().splitlines():
            m = line_pat.match(line)
            if not m:
                continue
            n = int(m.group(1))
            if 1 <= n <= 999 and n not in out:
                out[n] = f.parent.name
    return out


def from_the_document():
    rows, count = {}, None
    for line in (ROOT / "FINDINGS.md").read_text().splitlines():
        m = row_pat.match(line)
        if m:
            rows.setdefault(int(m.group(1)), m.group(2))
        m = count_pat.match(line)
        if m:
            count = int(m.group(1))
    return rows, count


def main():
    want = from_the_step0_files()
    got, count = from_the_document()
    problems = []
    if count is not None and count != len(want):
        problems.append(f"the document says {count} findings; the STEP0 files "
                        f"hold {len(want)}")
    for n in sorted(set(want) | set(got)):
        if n not in got:
            problems.append(f"finding {n} ({want[n]}) is not in the index")
        elif n not in want:
            problems.append(f"finding {n} is indexed but no STEP0.md claims it")
        elif want[n] != got[n]:
            problems.append(f"finding {n} is indexed under {got[n]}, "
                            f"but {want[n]} claims it")
    if not problems:
        return 0
    print("FINDINGS.md's index of numbered findings is stale:", file=sys.stderr)
    for p in problems[:12]:
        print(f"    {p}", file=sys.stderr)
    if len(problems) > 12:
        print(f"    ... and {len(problems) - 12} more", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
