"use client";

import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { useMemo, useRef } from "react";
import { Box3, Group, MathUtils, Vector3 } from "three";

/**
 * The E³ blading, turning on its two spools.
 *
 * This is the `TurbineStage` spool pattern — two independent rotating
 * groups at their own speeds — applied to real geometry rather than to
 * line art. Every blade in here was lofted from the section coordinates
 * NASA and GE published, and the file it comes from is generated by
 * `projects/09-e3-engine/solvers/publication/render.py`.
 *
 * The spool each row belongs to is NOT decided here. Every row node in the
 * glTF carries `extras.spool` — `lp`, `hp` or `static` — written by the
 * exporter from the same data that drives the mass roll-up, so this
 * component reads the engine's own architecture instead of pattern-matching
 * on names. Speeds come from `extras.kinematics`, which carries the
 * max-climb LP and HP rpm the reports reconcile to.
 *
 * What it does NOT claim: the relative rotation direction. The reports read
 * do not state it, so both spools co-rotate here as a recorded modelling
 * decision. It turns; it does not run.
 *
 * The canvas, lights, controls and the reduced-motion decision belong to
 * ModelStage — this is only the part that knows about spools.
 */

/** Slow the real rpm to something an eye can read, keeping the ratio exact. */
const DEMO_RPM_SCALE = 1 / 900;

export default function Blading({ src, spinning }) {
  const { scene } = useGLTF(src);
  const lp = useRef();
  const hp = useRef();

  // Split the scene into three groups once, by the spool each row declares.
  // Cloning is deliberate: useGLTF caches the parsed scene, and re-parenting
  // the cached one would corrupt it for any other mounted viewer.
  const { groups, rate, shiftX } = useMemo(() => {
    const root = scene.clone(true);
    const made = { lp: new Group(), hp: new Group(), static: new Group() };
    for (const child of [...root.children]) {
      const spool = child.userData?.spool ?? "static";
      (made[spool] ?? made.static).add(child);
    }

    // Centre in X ONLY. The rows are already built about the engine axis
    // (y = z = 0) and rotate about it; the cutaway removes a 75° wedge, so
    // the bounding box is deliberately NOT symmetric in y and z. Centring
    // on that box would push each spool off the axis and make it wobble.
    // X is safe because rotation about X does not move X.
    const box = new Box3().setFromObject(root);
    const centre = box.getCenter(new Vector3());

    const k = scene.userData?.kinematics ?? {};
    return {
      groups: made,
      shiftX: -centre.x,
      rate: {
        lp: ((k.rpm_lp ?? 3528.9) / 60) * 2 * Math.PI * DEMO_RPM_SCALE,
        hp: ((k.rpm_hp ?? 12645) / 60) * 2 * Math.PI * DEMO_RPM_SCALE,
      },
    };
  }, [scene]);

  useFrame((_, dt) => {
    if (!spinning) return;
    // Rotation is about +X: the engine axis in the exported file.
    if (lp.current) lp.current.rotation.x += rate.lp * dt;
    if (hp.current) hp.current.rotation.x += rate.hp * dt;
  });

  return (
    <group
      // Lay the engine's long axis across the viewport and tip it into a
      // three-quarter view, the angle a manufacturer's cutaway uses.
      rotation={[0, MathUtils.degToRad(-24), MathUtils.degToRad(10)]}
      scale={0.55}
    >
      {/* Each spool is a wrapper group whose rotation.x is animated. The
          rotation lives on the wrapper rather than on the loaded objects,
          so nothing in the cached glTF is ever mutated. */}
      <group ref={lp} position={[shiftX, 0, 0]}>
        <primitive object={groups.lp} />
      </group>
      <group ref={hp} position={[shiftX, 0, 0]}>
        <primitive object={groups.hp} />
      </group>
      <group position={[shiftX, 0, 0]}>
        <primitive object={groups.static} />
      </group>
    </group>
  );
}
