#!/usr/bin/env python3
"""Regenerate everything this project produces, from a clean clone.

Stage G's last bullet: *`build.py`: one command regenerates every table,
figure and export.* This is that command.

    python build.py                 # every stage's tables, the figures, the CAD
    python build.py --no-geometry   # skip the CAD, which is the slow part
    python build.py --list          # what would run, without running it

Every solver module in `solvers/` that has a `__main__` prints the table
its STEP0.md records. This runs them all, in stage order, and writes each
one's output to `build/<module>.txt` so a reader can diff a run against the
numbers quoted in the STEP0 files. Figures are regenerated by the modules
that own them. The CAD is unit G1's 32 blade rows, exported to STEP.

What this deliberately does NOT do is produce a number that is gated.
There is no basic-engine mass here, because F2's closure is gated on
un-digitised disc profiles and on a bearing system the reports never
dimension; there is no CFD, because C4 has no solver installed. A build
script that filled those in would be manufacturing agreement."""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOLVERS = ROOT / "solvers"
OUT = ROOT / "build"

# stage order, the same order WORK-PLAN.md uses
STAGES = [
    ("B  cycle", ["e3cycle.run", "e3cycle.stations"]),
    ("C1 mean-line", ["meanline.lpt", "meanline.lpt_losses", "meanline.hpt",
                      "meanline.compressor", "meanline.fan", "meanline.stage_counts",
                      "meanline.sections"]),
    ("C2 through-flow", ["throughflow.radial_equilibrium", "throughflow.predict",
                         "throughflow.lpt_vortex", "throughflow.hpt_spanwise"]),
    ("C3 blading", ["blading.sections", "blading.lpt_sections", "blading.hpt_sections",
                    "blading.fan_blade", "blading.run"]),
    ("D  thermal", ["thermal.cooling", "thermal.secondary_air", "thermal.clearance",
                    "thermal.combustor"]),
    ("E  mechanical", ["mechanical.blade_stress", "mechanical.disc",
                       "mechanical.blade_frequency", "mechanical.rotordynamics",
                       "mechanical.attachments", "mechanical.flutter", "mechanical.gas_bending"]),
    ("F  materials", ["materials.allowables", "materials.mass"]),
    ("G  geometry", ["geometry.blades"]),
    ("I  verification", ["verification.consistency", "verification.sensitivity",
                         "verification.disagreements",
                         "verification.digitising"]),
    ("J  publication", ["publication.meridional", "publication.campbell",
                        "publication.render", "publication.drawings"]),
]
GEOMETRY = {"geometry.blades"}


def run(module: str) -> tuple[bool, float, str]:
    t0 = time.time()
    p = subprocess.run([sys.executable, "-m", module], cwd=SOLVERS,
                       capture_output=True, text=True)
    text = p.stdout + (("\n--- stderr ---\n" + p.stderr) if p.stderr.strip() else "")
    (OUT / f"{module}.txt").write_text(text)
    return p.returncode == 0, time.time() - t0, text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--no-geometry", action="store_true",
                    help="skip unit G1's CAD, which is minutes rather than seconds")
    ap.add_argument("--list", action="store_true", help="print the plan and stop")
    ap.add_argument("--export", action="store_true",
                    help="also write the STEP files for every blade row")
    args = ap.parse_args()

    plan = [(stage, m) for stage, mods in STAGES for m in mods
            if not (args.no_geometry and m in GEOMETRY)]
    if args.list:
        for stage, m in plan:
            print(f"{stage:<18} {m}")
        print(f"\n{len(plan)} modules")
        return 0

    OUT.mkdir(exist_ok=True)
    failures, total = [], 0.0
    stage_seen = None
    for stage, module in plan:
        if stage != stage_seen:
            print(f"\n{stage}")
            stage_seen = stage
        ok, dt, _ = run(module)
        total += dt
        print(f"   {'ok ' if ok else 'FAIL'} {module:<34}{dt:>7.1f} s")
        if not ok:
            failures.append(module)

    if args.export and not args.no_geometry:
        print("\nSTEP export")
        sys.path.insert(0, str(SOLVERS))
        from geometry.blades import export          # noqa: E402
        t0 = time.time()
        written = export()
        print(f"   ok  {len(written)} files in exports/{'':<14}{time.time() - t0:>7.1f} s")

    print(f"\n{len(plan) - len(failures)} of {len(plan)} modules ran, {total:.0f} s total")
    print(f"output in build/ — diff it against the tables quoted in each STEP0.md")
    if failures:
        print(f"FAILED: {', '.join(failures)}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
