#!/usr/bin/env python3
"""Export the transcribed E3 blade sections for the Turbofan Atlas page.

Reads data/hpc-blade-sections.yaml (HPC Table XXII: 12 sections per row,
21 rows) and data/lpt-airfoils/*.csv (LPT appendix: 30 sections, 3 spans
per row, real surface coordinates), and writes one ES module,
app/turbofan/atlas/data/e3-sections.js, that the page lofts its HPC and
LPT blades from. Run from the repository root after either source changes.
"""
import csv, glob, json, math, os, re, sys
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
DATA = os.path.join(ROOT, "projects", "09-e3-engine", "data")
OUT = os.path.join(ROOT, "app", "turbofan", "atlas", "data", "e3-sections.js")

# ── HPC ────────────────────────────────────────────────────────────────────
y = yaml.safe_load(open(os.path.join(DATA, "hpc-blade-sections.yaml")))
hpc = {}
def rows(block, key):
    for item in block:
        secs = item["sections"]
        out = []
        for sec in reversed(secs):  # printed tip first; hub first here
            r_cm, chord_cm = sec[0], sec[2]
            if key == "IGV":
                stagger, cl0, tm = sec[4], sec[5], sec[6]
                camber = round(25.0 * cl0, 2)  # CL0 -> turning, schematic; the IGV prints no camber
            else:
                camber, stagger, tm = sec[4], sec[5], sec[8]
            out.append([round(r_cm / 100, 5), round(chord_cm / 100, 5), camber, stagger, tm])
        yield item.get("stage"), out
for stage, secs in rows(y["rotors"], "R"):
    hpc[f"R{stage}"] = secs
for stage, secs in rows(y["stators"], "S"):
    hpc[f"S{stage}"] = secs
hpc["IGV"] = next(rows([y["igv"]], "IGV"))[1]

# ── LPT ────────────────────────────────────────────────────────────────────
def resample(points, n):
    """Resample a polyline to n points spaced by arc length, cosine-clustered at the ends."""
    d = [0.0]
    for a, b in zip(points, points[1:]):
        d.append(d[-1] + math.dist(a, b))
    total = d[-1]
    out = []
    for i in range(n):
        s = i / (n - 1)
        t = (1 - math.cos(math.pi * s)) / 2 * total
        k = max(1, min(len(d) - 1, next((j for j in range(1, len(d)) if d[j] >= t), len(d) - 1)))
        f = 0 if d[k] == d[k - 1] else (t - d[k - 1]) / (d[k] - d[k - 1])
        out.append([points[k - 1][c] + f * (points[k][c] - points[k - 1][c]) for c in range(3)])
    return out

N = 14
lpt = {}
for path in sorted(glob.glob(os.path.join(DATA, "lpt-airfoils", "*.csv"))):
    name = os.path.basename(path)[:-4]
    row, span = name.split("_")
    suction, pressure = [], []
    with open(path) as f:
        for rec in csv.DictReader(l for l in f if not l.startswith("#")):
            # [r, z, rtheta] in metres; z from the HPT exit plane (the LPT datum)
            p = [float(rec["r_in"]) * 0.0254, float(rec["z_in"]) * 0.0254, float(rec["rtheta_in"]) * 0.0254]
            (suction if rec["surface"] == "suction" else pressure).append(p)
    s = resample(suction, N)
    q = resample(pressure, N)
    poly = s + list(reversed(q[1:-1]))  # closed loop: suction LE->TE, pressure TE->LE
    lpt.setdefault(row, {})[int(span)] = [[round(v, 5) for v in p] for p in poly]

def extrap(a, b, f):
    return [[round(a[i][c] + (b[i][c] - a[i][c]) * f, 5) for c in range(3)] for i in range(len(a))]
lpt_rows = {}
for row, spans in lpt.items():
    s10, s50, s90 = spans[10], spans[50], spans[90]
    # Hub and tip by straight-line extrapolation through 10 % and 50 % (and 50 % and 90 %),
    # the same rule data/lpt-flowpath.csv uses for the walls.
    lpt_rows[row] = [extrap(s10, s50, -0.25), s10, s50, s90, extrap(s50, s90, 1.25)]

with open(OUT, "w") as f:
    f.write("// GENERATED by projects/09-e3-engine/tools/export_atlas_sections.py — do not edit.\n")
    f.write("// HPC: Table XXII of the E³ HPC detail design report (NTRS 19850002690), 12 sections\n")
    f.write("// per row hub first as [r_m, chord_m, camber_deg, stagger_deg, tmax/chord]; the IGV's\n")
    f.write("// camber is 25×CL0 (schematic — the table prints CL0, not camber).\n")
    f.write("// LPT: the thirty transcribed airfoil sections of the E³ LPT report appendix, each\n")
    f.write("// resampled to %d points per surface as [r_m, z_m from the HPT exit plane, rtheta_m];\n" % N)
    f.write("// hub and tip extrapolated from the 10/50/90 % sections as the flowpath is.\n")
    f.write("export const HPC_SECTIONS = " + json.dumps(hpc, separators=(",", ":")) + ";\n")
    f.write("export const LPT_SECTIONS = " + json.dumps(lpt_rows, separators=(",", ":")) + ";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes;", len(hpc), "HPC rows,", len(lpt_rows), "LPT rows")
